// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	posts: R2Bucket;
	IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
