// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	posts: R2Bucket;
	IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
